nmHoistingLimits: none

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.10.3.cjs

packageExtensions:
  "@storybook/addon-docs@*":
    dependencies:
      "@types/react": "^19.0.0"
  "@storybook/addon-webpack5-compiler-babel@*":
    dependencies:
      "webpack": "^5.0.0"
  "storybook@*":
    dependencies:
      "@testing-library/dom": "^10.4.0"
