module.exports = [
  // Arrows
  "arrow-up.svg",
  "arrow-down.svg",
  "arrow-left.svg",
  "arrow-right.svg",
  "arrow-clockwise.svg",
  "arrow-90deg-down.svg",
  "arrow-90deg-up.svg",
  "arrow-return-left.svg",
  "arrow-90deg-left.svg",
  "arrow-return-right.svg",
  "arrow-90deg-right.svg",
  "arrows-move.svg",
  "arrows-expand.svg",
  "arrows-collapse.svg",
  "arrows-angle-expand.svg",
  "arrows-angle-contract.svg",
  "arrows-fullscreen.svg",

  // Shape arrows
  "arrow-up-circle-fill.svg",
  "arrow-up-circle.svg",
  "arrow-down-circle-fill.svg",
  "arrow-down-circle.svg",
  "arrow-left-circle-fill.svg",
  "arrow-left-circle.svg",
  "arrow-right-circle-fill.svg",
  "arrow-right-circle.svg",

  // Box arrows
  "box-arrow-in-right.svg",
  "box-arrow-right.svg",
  "box-arrow-in-up-right.svg",
  "box-arrow-up-right.svg",

  // Carrets
  "caret-up-fill.svg",
  "caret-down-fill.svg",
  "caret-left-fill.svg",
  "caret-right-fill.svg",

  // Chevrons
  "chevron-up.svg",
  "chevron-down.svg",
  "chevron-left.svg",
  "chevron-right.svg",
  "chevron-double-up.svg",
  "chevron-double-down.svg",
  "chevron-double-left.svg",
  "chevron-double-right.svg",

  // Alerts, warnings and signs
  "check-lg.svg",
  "check2.svg",
  "exclamation-lg.svg",
  "question-lg.svg",
  "info-lg.svg",
  "x-lg.svg",
  "plus-lg.svg",
  "dash-lg.svg",
  "check-circle.svg",
  "check-circle-fill.svg",
  "exclamation-circle.svg",
  "exclamation-circle-fill.svg",
  "exclamation-triangle-fill.svg",
  "question-circle.svg",
  "question-circle-fill.svg",
  "info-circle.svg",
  "info-circle-fill.svg",
  "x-circle.svg",
  "x-circle-fill.svg",
  "plus-circle.svg",
  "plus-circle-fill.svg",
  "dash-circle.svg",
  "dash-circle-fill.svg",
  "filter.svg",

  // Files and folders
  "file-earmark-pdf.svg",
  "file-arrow-down-fill.svg",
  "file-pdf-fill.svg",
  "file-earmark-bar-graph.svg",
  "file-bar-graph-fill.svg",
  "file-earmark-ppt.svg",
  "file-ppt-fill.svg",
  "file-earmark-excel.svg",
  "file-excel-fill.svg",
  "file-earmark-word.svg",
  "file-word-fill.svg",
  "file-earmark-image.svg",
  "file-image-fill.svg",
  "file-earmark-font.svg",
  "file-font-fill.svg",
  "file-earmark-slides.svg",
  "file-slides-fill.svg",
  "file-earmark-person.svg",
  "file-person-fill.svg",
  "file-earmark-music.svg",
  "file-music-fill.svg",
  "file-earmark-play.svg",
  "file-play-fill.svg",
  "file-earmark-code.svg",
  "file-code-fill.svg",
  "file-earmark-zip.svg",
  "file-zip-fill.svg",
  "file-earmark-text.svg",
  "file-text-fill.svg",
  "file-earmark.svg",
  "file-fill.svg",
  "folder.svg",
  "folder-fill.svg",

  // UI and keyboard
  "trash.svg",
  "trash-fill.svg",
  "link.svg",

  // Social.svg
  "skype.svg",
  "reddit.svg",
  "mastodon.svg",
  "messenger.svg",
  "whatsapp.svg",
  "telegram.svg",
  "discord.svg",
  "youtube.svg",
  "twitch.svg",
  "twitter.svg",
  "facebook.svg",
  "instagram.svg",
  "slack.svg",
  "linkedin.svg",
  "google.svg",
  "github.svg",

  // Shapes
  "heart.svg",
  "heart-fill.svg",
  "star.svg",
  "star-fill.svg",
  "star-half.svg",
  "diamond.svg",
  "diamond-fill.svg",
  "triangle.svg",
  "triangle-fill.svg",
  "square.svg",
  "square-fill.svg",
  "circle.svg",
  "circle-fill.svg",

  // Media
  "volume-off.svg",
  "volume-off-fill.svg",
  "volume-mute.svg",
  "volume-mute-fill.svg",
  "volume-up.svg",
  "volume-up-fill.svg",
  "volume-down.svg",
  "volume-down-fill.svg",
  "skip-forward.svg",
  "skip-forward-fill.svg",
  "skip-backward.svg",
  "skip-backward-fill.svg",
  "skip-end.svg",
  "skip-end-fill.svg",
  "skip-start.svg",
  "skip-start-fill.svg",
  "stop.svg",
  "stop-fill.svg",
  "pause.svg",
  "pause-fill.svg",
  "play.svg",
  "play-fill.svg",
  "record.svg",
  "record-fill.svg",

  // Devices
  "camera.svg",
  "camera-fill.svg",
  "printer.svg",
  "printer-fill.svg",
  "display.svg",
  "display-fill.svg",
  "tablet-landscape.svg",
  "tablet-landscape-fill.svg",
  "tablet.svg",
  "tablet-fill.svg",
  "phone-landscape.svg",
  "phone-landscape-fill.svg",
  "phone.svg",
  "phone-fill.svg",

  // Date and time
  "calendar-x.svg",
  "calendar-x-fill.svg",
  "calendar-check.svg",
  "calendar-check-fill.svg",
  "calendar-minus.svg",
  "calendar-minus-fill.svg",
  "clock-fill.svg",
  "calendar-plus.svg",
  "calendar-plus-fill.svg",
  "clock.svg",
  "calendar.svg",
  "calendar-fill.svg",

  // Communications
  "chat-left-quote.svg",
  "chat-left-quote-fill.svg",
  "chat-left-text.svg",
  "chat-left-text-fill.svg",
  "chat-left-dots.svg",
  "chat-left-dots-fill.svg",
  "chat-left.svg",
  "chat-left-fill.svg",
  "rss.svg",
  "rss-fill.svg",
  "envelope-open.svg",
  "envelope-open-fill.svg",
  "envelope.svg",
  "envelope-fill.svg",
  "archive.svg",
  "archive-fill.svg",
  "inboxes.svg",
  "inboxes-fill.svg",
  "wifi.svg",
  "inbox.svg",
  "inbox-fill.svg",
  "search.svg",
  "forward.svg",
  "forward-fill.svg",
  "reply-all.svg",
  "reply-all-fill.svg",
  "reply.svg",
  "reply-fill.svg",
  "globe2.svg",
  "flag.svg",
  "flag-fill.svg",
  "broadcast.svg",
  "bell-slash.svg",
  "bell-slash-fill.svg",
  "bell.svg",
  "bell-fill.svg",
  "telephone.svg",
  "telephone-fill.svg",
  "translate.svg",

  // Tools
  "gear.svg",
  "gear-fill.svg",
  "pencil-square.svg",
  "pencil.svg",
  "pencil-fill.svg",

  // Real world
  "key.svg",
  "key-fill.svg",
  "paperclip.svg",
  "funnel.svg",
  "funnel-fill.svg",
  "trophy.svg",
  "trophy-fill.svg",
  "award.svg",
  "award-fill.svg",
  "tag.svg",
  "tag-fill.svg",
  "sticky.svg",
  "sticky-fill.svg",
  "gift-fill.svg",
  "eye-slash.svg",
  "eye-slash-fill.svg",
  "signpost-split.svg",
  "signpost-split-fill.svg",
  "eye.svg",
  "eye-fill.svg",
  "house.svg",
  "house-fill.svg",
  "pin-fill.svg",

  // Geo
  "geo-alt.svg",
  "geo-alt-fill.svg",

  // Graphics
  "zoom-in.svg",
  "zoom-out.svg",

  // Emoji
  "emoji-neutral.svg",
  "emoji-neutral-fill.svg",
  "emoji-frown.svg",
  "emoji-frown-fill.svg",
  "emoji-smile.svg",
  "emoji-smile-fill.svg",

  // Hands
  "hand-thumbs-down.svg",
  "hand-thumbs-down-fill.svg",
  "hand-thumbs-up.svg",
  "hand-thumbs-up-fill.svg",

  // People
  "person-square.svg",
  "person-lines-fill.svg",
  "building.svg",
  "person-x.svg",
  "person-x-fill.svg",
  "person-check.svg",
  "person-check-fill.svg",
  "person-dash.svg",
  "person-dash-fill.svg",
  "person-plus.svg",
  "person-plus-fill.svg",
  "people.svg",
  "people-fill.svg",
  "person.svg",
  "person-fill.svg",

  // Security
  "unlock.svg",
  "unlock-fill.svg",
  "lock.svg",
  "lock-fill.svg",
  "shield-exclamation.svg",
  "shield-fill-exclamation.svg",
  "shield-x.svg",
  "shield-fill-x.svg",
  "shield-check.svg",
  "shield-fill-check.svg",

  // Cloud
  "cloud-arrow-up-fill.svg",
  "cloud-arrow-up.svg",
  "cloud-arrow-down-fill.svg",
  "cloud-arrow-down.svg",

  // Misc
  "upload.svg",
  "download.svg",
  "bookmarks.svg",
  "bookmarks-fill.svg",

  // Needed by paragraphs OEL-1348
  "book.svg",
  "check.svg",
  "currency-euro.svg",
  "file.svg",
  "filter.svg",
  "box-arrow-up.svg",
  "image.svg",
  "info.svg",
  "files.svg",
  "share.svg",
  "camera-video.svg",
];
