# .github/workflows/chromatic.yml

# Workflow name
name: 'deployment on chromatic'

# Event for the workflow
on: 
  push:
    branches-ignore:
      - "master"
      - "dependabot/**"
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Publish "default" to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: "build:chromatic:default"
          ci: true
          output-dir: "./storybook-static"
          exitOnceUploaded: true
          exitZeroOnChanges: true
      - name: Publish "joinup" to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: "build:chromatic:joinup"
          ci: true
          output-dir: "./storybook-static"
          exitOnceUploaded: true
          exitZeroOnChanges: true
      - name: Publish "ucpkn" to Chromatic
        uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          buildScriptName: "build:chromatic:ucpkn"
          ci: true
          output-dir: "./storybook-static"
          exitOnceUploaded: true
          exitZeroOnChanges: true