name: Dependency Review

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

permissions:
  contents: read

jobs:
  dependency-review:
    name: dependency review
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Dependency review
        uses: actions/dependency-review-action@v5
        with:
          fail-on-severity: low
          fail-on-scopes: runtime, development
          license-check: false
          vulnerability-check: true
          show-openssf-scorecard: false
          show-patched-versions: true
